# General options
general: 
    name: "Imported_Test"     # Name of the output folder
    preappend_datetime: false  # Place the date and time before the folder name

# Wind Farm constants for a grid farm
wind_farm: 
    #                     # Description              | Units
    HH: 90                # Hub Height               | m
    RD: 126.0             # Turbine Diameter         | m
    thickness: 10.5       # Effective Thickness      | m
    yaw: 0.0              # Yaw                      | rads
    axial: 0.33           # Axial Induction          | -
    ex_x: [-1250, 1250]   # x-extent of the farm     | m
    ex_y: [-1000, 1000]   # y-extent of the farm     | m
    ex_z: [0, 216]        # z-extent of the farm     | m
    grid_rows: 6          # Number of rows           | -
    grid_cols: 6          # Number of columns        | -
    numturbs: 36          # Number of Turbines       | -
    A: 126.0              # Area of the disk         | m^2
    alpha: 0.0            # Wind Direction           | rads
    beta: 2173.8621817909 # Normalization Constant   | ???

# Domain Constants for a Box Domain
domain: 
    #            # Description               | Units
    path: "Mesh_Data/"